pool:
	vmImage: 'ubuntu-18.04'
trigger:
	- master
steps:
	- task: CopyFiles@2
		inputs:
    		SourceFolder: 'deployment'
    		Contents: '*.json'
    		TargetFolder: '$(build.artifactstagingdirectory)/Templates'
	- task: Npm@1
		displayName: 'npm custom'
		inputs:
			command: custom
			verbose: false
			customCommand: 'install --production'
	- task: ArchiveFiles@2
		displayName: 'Archive $(Build.SourcesDirectory)'
		inputs:
			rootFolderOrFile: '$(Build.SourcesDirectory)'
			includeRootFolder: false
	- task: PublishPipelineArtifact@1
		inputs:
			targetPath: '$(Build.ArtifactstagingDirectory)'
			artifact: 'drop'
			publishLocation: 'pipeline'